package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

/**
 * PmaBookmark generated by hbm2java
 */
public class PmaBookmark implements java.io.Serializable {

	private Integer id;
	private String dbase;
	private String user;
	private String label;
	private String query;

	public PmaBookmark() {
	}

	public PmaBookmark(String dbase, String user, String label, String query) {
		this.dbase = dbase;
		this.user = user;
		this.label = label;
		this.query = query;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDbase() {
		return this.dbase;
	}

	public void setDbase(String dbase) {
		this.dbase = dbase;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

}
