package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

import java.util.Date;

/**
 * PmaHistory generated by hbm2java
 */
public class PmaHistory implements java.io.Serializable {

	private Long id;
	private String username;
	private String db;
	private String table;
	private Date timevalue;
	private String sqlquery;

	public PmaHistory() {
	}

	public PmaHistory(String username, String db, String table, Date timevalue, String sqlquery) {
		this.username = username;
		this.db = db;
		this.table = table;
		this.timevalue = timevalue;
		this.sqlquery = sqlquery;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getDb() {
		return this.db;
	}

	public void setDb(String db) {
		this.db = db;
	}

	public String getTable() {
		return this.table;
	}

	public void setTable(String table) {
		this.table = table;
	}

	public Date getTimevalue() {
		return this.timevalue;
	}

	public void setTimevalue(Date timevalue) {
		this.timevalue = timevalue;
	}

	public String getSqlquery() {
		return this.sqlquery;
	}

	public void setSqlquery(String sqlquery) {
		this.sqlquery = sqlquery;
	}

}
