package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

/**
 * PmaNavigationhiding generated by hbm2java
 */
public class PmaNavigationhiding implements java.io.Serializable {

	private PmaNavigationhidingId id;

	public PmaNavigationhiding() {
	}

	public PmaNavigationhiding(PmaNavigationhidingId id) {
		this.id = id;
	}

	public PmaNavigationhidingId getId() {
		return this.id;
	}

	public void setId(PmaNavigationhidingId id) {
		this.id = id;
	}

}
