package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

/**
 * PmaPdfPages generated by hbm2java
 */
public class PmaPdfPages implements java.io.Serializable {

	private Integer pageNr;
	private String dbName;
	private String pageDescr;

	public PmaPdfPages() {
	}

	public PmaPdfPages(String dbName, String pageDescr) {
		this.dbName = dbName;
		this.pageDescr = pageDescr;
	}

	public Integer getPageNr() {
		return this.pageNr;
	}

	public void setPageNr(Integer pageNr) {
		this.pageNr = pageNr;
	}

	public String getDbName() {
		return this.dbName;
	}

	public void setDbName(String dbName) {
		this.dbName = dbName;
	}

	public String getPageDescr() {
		return this.pageDescr;
	}

	public void setPageDescr(String pageDescr) {
		this.pageDescr = pageDescr;
	}

}
