package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

/**
 * PmaTableCoords generated by hbm2java
 */
public class PmaTableCoords implements java.io.Serializable {

	private PmaTableCoordsId id;
	private float x;
	private float y;

	public PmaTableCoords() {
	}

	public PmaTableCoords(PmaTableCoordsId id, float x, float y) {
		this.id = id;
		this.x = x;
		this.y = y;
	}

	public PmaTableCoordsId getId() {
		return this.id;
	}

	public void setId(PmaTableCoordsId id) {
		this.id = id;
	}

	public float getX() {
		return this.x;
	}

	public void setX(float x) {
		this.x = x;
	}

	public float getY() {
		return this.y;
	}

	public void setY(float y) {
		this.y = y;
	}

}
