package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

/**
 * PmaTableInfo generated by hbm2java
 */
public class PmaTableInfo implements java.io.Serializable {

	private PmaTableInfoId id;
	private String displayField;

	public PmaTableInfo() {
	}

	public PmaTableInfo(PmaTableInfoId id, String displayField) {
		this.id = id;
		this.displayField = displayField;
	}

	public PmaTableInfoId getId() {
		return this.id;
	}

	public void setId(PmaTableInfoId id) {
		this.id = id;
	}

	public String getDisplayField() {
		return this.displayField;
	}

	public void setDisplayField(String displayField) {
		this.displayField = displayField;
	}

}
