package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

/**
 * PmaUsers generated by hbm2java
 */
public class PmaUsers implements java.io.Serializable {

	private PmaUsersId id;

	public PmaUsers() {
	}

	public PmaUsers(PmaUsersId id) {
		this.id = id;
	}

	public PmaUsersId getId() {
		return this.id;
	}

	public void setId(PmaUsersId id) {
		this.id = id;
	}

}
