package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

/**
 * PmaUsergroups generated by hbm2java
 */
public class PmaUsergroups implements java.io.Serializable {

	private PmaUsergroupsId id;

	public PmaUsergroups() {
	}

	public PmaUsergroups(PmaUsergroupsId id) {
		this.id = id;
	}

	public PmaUsergroupsId getId() {
		return this.id;
	}

	public void setId(PmaUsergroupsId id) {
		this.id = id;
	}

}
