package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

import java.util.Date;

/**
 * PmaUserconfig generated by hbm2java
 */
public class PmaUserconfig implements java.io.Serializable {

	private String username;
	private Date timevalue;
	private String configData;

	public PmaUserconfig() {
	}

	public PmaUserconfig(String username, Date timevalue, String configData) {
		this.username = username;
		this.timevalue = timevalue;
		this.configData = configData;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Date getTimevalue() {
		return this.timevalue;
	}

	public void setTimevalue(Date timevalue) {
		this.timevalue = timevalue;
	}

	public String getConfigData() {
		return this.configData;
	}

	public void setConfigData(String configData) {
		this.configData = configData;
	}

}
