package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

import java.util.Date;

/**
 * TAvancement generated by hbm2java
 */
public class TAvancement implements java.io.Serializable {

	private Integer id;
	private THistoriqueAv THistoriqueAv;
	private TPersonnels TPersonnels;
	private TSalaire TSalaire;
	private String nom;
	private String qualification;
	private String cat;
	private String SCat;
	private String ech;
	private String sbase;
	private String th;
	private String indDiff;
	private Date DEffet;
	private Date DPAv;
	private String observation;
	private int active;

	public TAvancement() {
	}

	public TAvancement(TPersonnels TPersonnels, String nom, Date DEffet, int active) {
		this.TPersonnels = TPersonnels;
		this.nom = nom;
		this.DEffet = DEffet;
		this.active = active;
	}

	public TAvancement(THistoriqueAv THistoriqueAv, TPersonnels TPersonnels, TSalaire TSalaire, String nom,
			String qualification, String cat, String SCat, String ech, String sbase, String th, String indDiff,
			Date DEffet, Date DPAv, String observation, int active) {
		this.THistoriqueAv = THistoriqueAv;
		this.TPersonnels = TPersonnels;
		this.TSalaire = TSalaire;
		this.nom = nom;
		this.qualification = qualification;
		this.cat = cat;
		this.SCat = SCat;
		this.ech = ech;
		this.sbase = sbase;
		this.th = th;
		this.indDiff = indDiff;
		this.DEffet = DEffet;
		this.DPAv = DPAv;
		this.observation = observation;
		this.active = active;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public THistoriqueAv getTHistoriqueAv() {
		return this.THistoriqueAv;
	}

	public void setTHistoriqueAv(THistoriqueAv THistoriqueAv) {
		this.THistoriqueAv = THistoriqueAv;
	}

	public TPersonnels getTPersonnels() {
		return this.TPersonnels;
	}

	public void setTPersonnels(TPersonnels TPersonnels) {
		this.TPersonnels = TPersonnels;
	}

	public TSalaire getTSalaire() {
		return this.TSalaire;
	}

	public void setTSalaire(TSalaire TSalaire) {
		this.TSalaire = TSalaire;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	public String getCat() {
		return this.cat;
	}

	public void setCat(String cat) {
		this.cat = cat;
	}

	public String getSCat() {
		return this.SCat;
	}

	public void setSCat(String SCat) {
		this.SCat = SCat;
	}

	public String getEch() {
		return this.ech;
	}

	public void setEch(String ech) {
		this.ech = ech;
	}

	public String getSbase() {
		return this.sbase;
	}

	public void setSbase(String sbase) {
		this.sbase = sbase;
	}

	public String getTh() {
		return this.th;
	}

	public void setTh(String th) {
		this.th = th;
	}

	public String getIndDiff() {
		return this.indDiff;
	}

	public void setIndDiff(String indDiff) {
		this.indDiff = indDiff;
	}

	public Date getDEffet() {
		return this.DEffet;
	}

	public void setDEffet(Date DEffet) {
		this.DEffet = DEffet;
	}

	public Date getDPAv() {
		return this.DPAv;
	}

	public void setDPAv(Date DPAv) {
		this.DPAv = DPAv;
	}

	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

}
