package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TContratParent generated by hbm2java
 */
public class TContratParent implements java.io.Serializable {

	private Integer id;
	private String mle;
	private String nom;
	private Date dateEntreeEtab;
	private String type;
	private int active;
	private Set TPersonnelses = new HashSet(0);

	public TContratParent() {
	}

	public TContratParent(String mle, String nom, Date dateEntreeEtab, String type, int active) {
		this.mle = mle;
		this.nom = nom;
		this.dateEntreeEtab = dateEntreeEtab;
		this.type = type;
		this.active = active;
	}

	public TContratParent(String mle, String nom, Date dateEntreeEtab, String type, int active, Set TPersonnelses) {
		this.mle = mle;
		this.nom = nom;
		this.dateEntreeEtab = dateEntreeEtab;
		this.type = type;
		this.active = active;
		this.TPersonnelses = TPersonnelses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMle() {
		return this.mle;
	}

	public void setMle(String mle) {
		this.mle = mle;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Date getDateEntreeEtab() {
		return this.dateEntreeEtab;
	}

	public void setDateEntreeEtab(Date dateEntreeEtab) {
		this.dateEntreeEtab = dateEntreeEtab;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public Set getTPersonnelses() {
		return this.TPersonnelses;
	}

	public void setTPersonnelses(Set TPersonnelses) {
		this.TPersonnelses = TPersonnelses;
	}

}
