package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

import java.util.Date;

/**
 * TContratDetails generated by hbm2java
 */
public class TContratDetails implements java.io.Serializable {

	private Integer id;
	private int idContratParent;
	private Date dateD;
	private Date dateF;
	private String jours;
	private String mois;
	private String annee;
	private String qualification;
	private String type;
	private String ref;
	private Date dateRef;
	private String cddFile;
	private Integer idAv;

	public TContratDetails() {
	}

	public TContratDetails(int idContratParent, Date dateD, Date dateF, String jours, String qualification,
			String type) {
		this.idContratParent = idContratParent;
		this.dateD = dateD;
		this.dateF = dateF;
		this.jours = jours;
		this.qualification = qualification;
		this.type = type;
	}

	public TContratDetails(int idContratParent, Date dateD, Date dateF, String jours, String mois, String annee,
			String qualification, String type, String ref, Date dateRef, String cddFile, Integer idAv) {
		this.idContratParent = idContratParent;
		this.dateD = dateD;
		this.dateF = dateF;
		this.jours = jours;
		this.mois = mois;
		this.annee = annee;
		this.qualification = qualification;
		this.type = type;
		this.ref = ref;
		this.dateRef = dateRef;
		this.cddFile = cddFile;
		this.idAv = idAv;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdContratParent() {
		return this.idContratParent;
	}

	public void setIdContratParent(int idContratParent) {
		this.idContratParent = idContratParent;
	}

	public Date getDateD() {
		return this.dateD;
	}

	public void setDateD(Date dateD) {
		this.dateD = dateD;
	}

	public Date getDateF() {
		return this.dateF;
	}

	public void setDateF(Date dateF) {
		this.dateF = dateF;
	}

	public String getJours() {
		return this.jours;
	}

	public void setJours(String jours) {
		this.jours = jours;
	}

	public String getMois() {
		return this.mois;
	}

	public void setMois(String mois) {
		this.mois = mois;
	}

	public String getAnnee() {
		return this.annee;
	}

	public void setAnnee(String annee) {
		this.annee = annee;
	}

	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

	public Date getDateRef() {
		return this.dateRef;
	}

	public void setDateRef(Date dateRef) {
		this.dateRef = dateRef;
	}

	public String getCddFile() {
		return this.cddFile;
	}

	public void setCddFile(String cddFile) {
		this.cddFile = cddFile;
	}

	public Integer getIdAv() {
		return this.idAv;
	}

	public void setIdAv(Integer idAv) {
		this.idAv = idAv;
	}

}
