package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * THistoriqueAv generated by hbm2java
 */
public class THistoriqueAv implements java.io.Serializable {

	private Integer id;
	private String mle;
	private String nom;
	private String qualification;
	private String catA;
	private String catN;
	private String SCatA;
	private String SCatN;
	private String echA;
	private String echN;
	private String sbaseA;
	private String sbaseN;
	private String thA;
	private String thN;
	private String indDiffA;
	private String indDiffN;
	private Date DEffetA;
	private Date DEffetN;
	private Date DPAvA;
	private Date DPAvN;
	private int active;
	private String observation;
	private float note;
	private String san1;
	private String san2;
	private Set TAvancements = new HashSet(0);

	public THistoriqueAv() {
	}

	public THistoriqueAv(String mle, String nom, Date DEffetA, Date DEffetN, Date DPAvA, Date DPAvN, int active,
			float note) {
		this.mle = mle;
		this.nom = nom;
		this.DEffetA = DEffetA;
		this.DEffetN = DEffetN;
		this.DPAvA = DPAvA;
		this.DPAvN = DPAvN;
		this.active = active;
		this.note = note;
	}

	public THistoriqueAv(String mle, String nom, String qualification, String catA, String catN, String SCatA,
			String SCatN, String echA, String echN, String sbaseA, String sbaseN, String thA, String thN,
			String indDiffA, String indDiffN, Date DEffetA, Date DEffetN, Date DPAvA, Date DPAvN, int active,
			String observation, float note, String san1, String san2, Set TAvancements) {
		this.mle = mle;
		this.nom = nom;
		this.qualification = qualification;
		this.catA = catA;
		this.catN = catN;
		this.SCatA = SCatA;
		this.SCatN = SCatN;
		this.echA = echA;
		this.echN = echN;
		this.sbaseA = sbaseA;
		this.sbaseN = sbaseN;
		this.thA = thA;
		this.thN = thN;
		this.indDiffA = indDiffA;
		this.indDiffN = indDiffN;
		this.DEffetA = DEffetA;
		this.DEffetN = DEffetN;
		this.DPAvA = DPAvA;
		this.DPAvN = DPAvN;
		this.active = active;
		this.observation = observation;
		this.note = note;
		this.san1 = san1;
		this.san2 = san2;
		this.TAvancements = TAvancements;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMle() {
		return this.mle;
	}

	public void setMle(String mle) {
		this.mle = mle;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	public String getCatA() {
		return this.catA;
	}

	public void setCatA(String catA) {
		this.catA = catA;
	}

	public String getCatN() {
		return this.catN;
	}

	public void setCatN(String catN) {
		this.catN = catN;
	}

	public String getSCatA() {
		return this.SCatA;
	}

	public void setSCatA(String SCatA) {
		this.SCatA = SCatA;
	}

	public String getSCatN() {
		return this.SCatN;
	}

	public void setSCatN(String SCatN) {
		this.SCatN = SCatN;
	}

	public String getEchA() {
		return this.echA;
	}

	public void setEchA(String echA) {
		this.echA = echA;
	}

	public String getEchN() {
		return this.echN;
	}

	public void setEchN(String echN) {
		this.echN = echN;
	}

	public String getSbaseA() {
		return this.sbaseA;
	}

	public void setSbaseA(String sbaseA) {
		this.sbaseA = sbaseA;
	}

	public String getSbaseN() {
		return this.sbaseN;
	}

	public void setSbaseN(String sbaseN) {
		this.sbaseN = sbaseN;
	}

	public String getThA() {
		return this.thA;
	}

	public void setThA(String thA) {
		this.thA = thA;
	}

	public String getThN() {
		return this.thN;
	}

	public void setThN(String thN) {
		this.thN = thN;
	}

	public String getIndDiffA() {
		return this.indDiffA;
	}

	public void setIndDiffA(String indDiffA) {
		this.indDiffA = indDiffA;
	}

	public String getIndDiffN() {
		return this.indDiffN;
	}

	public void setIndDiffN(String indDiffN) {
		this.indDiffN = indDiffN;
	}

	public Date getDEffetA() {
		return this.DEffetA;
	}

	public void setDEffetA(Date DEffetA) {
		this.DEffetA = DEffetA;
	}

	public Date getDEffetN() {
		return this.DEffetN;
	}

	public void setDEffetN(Date DEffetN) {
		this.DEffetN = DEffetN;
	}

	public Date getDPAvA() {
		return this.DPAvA;
	}

	public void setDPAvA(Date DPAvA) {
		this.DPAvA = DPAvA;
	}

	public Date getDPAvN() {
		return this.DPAvN;
	}

	public void setDPAvN(Date DPAvN) {
		this.DPAvN = DPAvN;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	public float getNote() {
		return this.note;
	}

	public void setNote(float note) {
		this.note = note;
	}

	public String getSan1() {
		return this.san1;
	}

	public void setSan1(String san1) {
		this.san1 = san1;
	}

	public String getSan2() {
		return this.san2;
	}

	public void setSan2(String san2) {
		this.san2 = san2;
	}

	public Set getTAvancements() {
		return this.TAvancements;
	}

	public void setTAvancements(Set TAvancements) {
		this.TAvancements = TAvancements;
	}

}
