package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TPersonnels generated by hbm2java
 */
public class TPersonnels implements java.io.Serializable {

	private TPersonnelsId id;
	private TContratParent TContratParent;
	private String nom;
	private String prenom;
	private String nomP;
	private String nomM;
	private String dateN;
	private String lieuN;
	private String cin;
	private String cpostal;
	private Date dateCin;
	private String numCnss;
	private String adresse;
	private String ville;
	private String SF;
	private String sexe;
	private Date dateEntreEtab;
	private Date dateAnc;
	private Date dateSortieEtab;
	private String motifSortie;
	private String tel;
	private Set TAvancements = new HashSet(0);

	public TPersonnels() {
	}

	public TPersonnels(TPersonnelsId id, String nom, String prenom) {
		this.id = id;
		this.nom = nom;
		this.prenom = prenom;
	}

	public TPersonnels(TPersonnelsId id, TContratParent TContratParent, String nom, String prenom, String nomP,
			String nomM, String dateN, String lieuN, String cin, String cpostal, Date dateCin, String numCnss,
			String adresse, String ville, String SF, String sexe, Date dateEntreEtab, Date dateAnc, Date dateSortieEtab,
			String motifSortie, String tel, Set TAvancements) {
		this.id = id;
		this.TContratParent = TContratParent;
		this.nom = nom;
		this.prenom = prenom;
		this.nomP = nomP;
		this.nomM = nomM;
		this.dateN = dateN;
		this.lieuN = lieuN;
		this.cin = cin;
		this.cpostal = cpostal;
		this.dateCin = dateCin;
		this.numCnss = numCnss;
		this.adresse = adresse;
		this.ville = ville;
		this.SF = SF;
		this.sexe = sexe;
		this.dateEntreEtab = dateEntreEtab;
		this.dateAnc = dateAnc;
		this.dateSortieEtab = dateSortieEtab;
		this.motifSortie = motifSortie;
		this.tel = tel;
		this.TAvancements = TAvancements;
	}

	public TPersonnelsId getId() {
		return this.id;
	}

	public void setId(TPersonnelsId id) {
		this.id = id;
	}

	public TContratParent getTContratParent() {
		return this.TContratParent;
	}

	public void setTContratParent(TContratParent TContratParent) {
		this.TContratParent = TContratParent;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getNomP() {
		return this.nomP;
	}

	public void setNomP(String nomP) {
		this.nomP = nomP;
	}

	public String getNomM() {
		return this.nomM;
	}

	public void setNomM(String nomM) {
		this.nomM = nomM;
	}

	public String getDateN() {
		return this.dateN;
	}

	public void setDateN(String dateN) {
		this.dateN = dateN;
	}

	public String getLieuN() {
		return this.lieuN;
	}

	public void setLieuN(String lieuN) {
		this.lieuN = lieuN;
	}

	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	public String getCpostal() {
		return this.cpostal;
	}

	public void setCpostal(String cpostal) {
		this.cpostal = cpostal;
	}

	public Date getDateCin() {
		return this.dateCin;
	}

	public void setDateCin(Date dateCin) {
		this.dateCin = dateCin;
	}

	public String getNumCnss() {
		return this.numCnss;
	}

	public void setNumCnss(String numCnss) {
		this.numCnss = numCnss;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public String getSF() {
		return this.SF;
	}

	public void setSF(String SF) {
		this.SF = SF;
	}

	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	public Date getDateEntreEtab() {
		return this.dateEntreEtab;
	}

	public void setDateEntreEtab(Date dateEntreEtab) {
		this.dateEntreEtab = dateEntreEtab;
	}

	public Date getDateAnc() {
		return this.dateAnc;
	}

	public void setDateAnc(Date dateAnc) {
		this.dateAnc = dateAnc;
	}

	public Date getDateSortieEtab() {
		return this.dateSortieEtab;
	}

	public void setDateSortieEtab(Date dateSortieEtab) {
		this.dateSortieEtab = dateSortieEtab;
	}

	public String getMotifSortie() {
		return this.motifSortie;
	}

	public void setMotifSortie(String motifSortie) {
		this.motifSortie = motifSortie;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public Set getTAvancements() {
		return this.TAvancements;
	}

	public void setTAvancements(Set TAvancements) {
		this.TAvancements = TAvancements;
	}

}
