package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

/**
 * TPersonnelsId generated by hbm2java
 */
public class TPersonnelsId implements java.io.Serializable {

	private int id;
	private String mle;

	public TPersonnelsId() {
	}

	public TPersonnelsId(int id, String mle) {
		this.id = id;
		this.mle = mle;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getMle() {
		return this.mle;
	}

	public void setMle(String mle) {
		this.mle = mle;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TPersonnelsId))
			return false;
		TPersonnelsId castOther = (TPersonnelsId) other;

		return (this.getId() == castOther.getId()) && ((this.getMle() == castOther.getMle())
				|| (this.getMle() != null && castOther.getMle() != null && this.getMle().equals(castOther.getMle())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getMle() == null ? 0 : this.getMle().hashCode());
		return result;
	}

}
