package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

import java.util.Date;

/**
 * TPostes generated by hbm2java
 */
public class TPostes implements java.io.Serializable {

	private TPostesId id;
	private TDepartements TDepartements;
	private String fonction;
	private String position;
	private String qualification;
	private String college;
	private String active;
	private Date datePoste;
	private String idService;
	private String nomService;
	private String ref;

	public TPostes() {
	}

	public TPostes(TPostesId id, TDepartements TDepartements, String qualification, String college, Date datePoste,
			String ref) {
		this.id = id;
		this.TDepartements = TDepartements;
		this.qualification = qualification;
		this.college = college;
		this.datePoste = datePoste;
		this.ref = ref;
	}

	public TPostes(TPostesId id, TDepartements TDepartements, String fonction, String position, String qualification,
			String college, String active, Date datePoste, String idService, String nomService, String ref) {
		this.id = id;
		this.TDepartements = TDepartements;
		this.fonction = fonction;
		this.position = position;
		this.qualification = qualification;
		this.college = college;
		this.active = active;
		this.datePoste = datePoste;
		this.idService = idService;
		this.nomService = nomService;
		this.ref = ref;
	}

	public TPostesId getId() {
		return this.id;
	}

	public void setId(TPostesId id) {
		this.id = id;
	}

	public TDepartements getTDepartements() {
		return this.TDepartements;
	}

	public void setTDepartements(TDepartements TDepartements) {
		this.TDepartements = TDepartements;
	}

	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	public String getCollege() {
		return this.college;
	}

	public void setCollege(String college) {
		this.college = college;
	}

	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	public Date getDatePoste() {
		return this.datePoste;
	}

	public void setDatePoste(Date datePoste) {
		this.datePoste = datePoste;
	}

	public String getIdService() {
		return this.idService;
	}

	public void setIdService(String idService) {
		this.idService = idService;
	}

	public String getNomService() {
		return this.nomService;
	}

	public void setNomService(String nomService) {
		this.nomService = nomService;
	}

	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

}
