package com.rahma.AvEchelon.Entity;
// Generated Jun 13, 2024, 2:26:21 AM by Hibernate Tools 5.6.7.Final

import java.util.Date;

/**
 * TSanctions generated by hbm2java
 */
public class TSanctions implements java.io.Serializable {

	private Integer id;
	private String mle;
	private String sanction;
	private Date DDebut;
	private Integer duree;
	private Date DFin;
	private String motif;
	private String ref;
	private Date dateRef;

	public TSanctions() {
	}

	public TSanctions(String mle, String sanction, Date DDebut, String motif) {
		this.mle = mle;
		this.sanction = sanction;
		this.DDebut = DDebut;
		this.motif = motif;
	}

	public TSanctions(String mle, String sanction, Date DDebut, Integer duree, Date DFin, String motif, String ref,
			Date dateRef) {
		this.mle = mle;
		this.sanction = sanction;
		this.DDebut = DDebut;
		this.duree = duree;
		this.DFin = DFin;
		this.motif = motif;
		this.ref = ref;
		this.dateRef = dateRef;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMle() {
		return this.mle;
	}

	public void setMle(String mle) {
		this.mle = mle;
	}

	public String getSanction() {
		return this.sanction;
	}

	public void setSanction(String sanction) {
		this.sanction = sanction;
	}

	public Date getDDebut() {
		return this.DDebut;
	}

	public void setDDebut(Date DDebut) {
		this.DDebut = DDebut;
	}

	public Integer getDuree() {
		return this.duree;
	}

	public void setDuree(Integer duree) {
		this.duree = duree;
	}

	public Date getDFin() {
		return this.DFin;
	}

	public void setDFin(Date DFin) {
		this.DFin = DFin;
	}

	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

	public Date getDateRef() {
		return this.dateRef;
	}

	public void setDateRef(Date dateRef) {
		this.dateRef = dateRef;
	}

}
